spring:
  datasource:
    url: jdbc:postgresql://dpg-cld5acjmot1c73dldqt0-a.singapore-postgres.render.com/emp_kcy2
    username: emp_kcy2_user
    password: VbKBkto1bkjYFoKWIUCaZ6y5xROcQi7M


  jpa:
    hibernate:
      ddl-auto: update # Change to "create" if you want to recreate the schema on each run (for development only)
    show-sql: true # Enable to see SQL queries in the console (for debugging)
